version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/AICTE_PORTAL_SIH_2022
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: ec2-user
  Install:
    - location: scripts/install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user