version: '3.9'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    volumes:
      - ./data/kafka:/var/run/docker.sock
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    ports:
      - "4000:4000"
    volumes:
      - ./api-gateway:/app
    networks:
      - aicte-network
  users:
    container_name: users
    build: ./users
    ports:
      - 4001:4000
    volumes:
      - ./users:/app
    environment:
      - PORT=4000
      - CASSANDRA_HOST=cassandra.ap-south-1.amazonaws.com
      - CASSANDRA_REGION=ap-south-1
      - CASSANDRA_USERNAME=Divyanshu-at-179683962947
      - CASSANDRA_PASSWORD=rIB+JBT0gofd1TZFrTLq2Ras0nUBA+QO3yoOvu0iFnE=
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=auth
    networks:
      - aicte-network
  venue:
    container_name: venue
    build: ./venue
    ports:
      - 4002:4000
    volumes:
      - ./venue:/app
    environment:
      - PORT=4000
      - CASSANDRA_HOST=cassandra.ap-south-1.amazonaws.com
      - CASSANDRA_REGION=ap-south-1
      - CASSANDRA_USERNAME=Divyanshu-at-179683962947
      - CASSANDRA_PASSWORD=rIB+JBT0gofd1TZFrTLq2Ras0nUBA+QO3yoOvu0iFnE=
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=auth
    networks:
      - aicte-network
networks:
  aicte-network:
    driver: bridge