version: '3.9'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    volumes:
      - ./data/kafka:/var/run/docker.sock
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  # mongo:
  #   container_name: mongo
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./data/mongo:/data/db
  #   networks:
  #     - aicte-network 
  # mongo-express:
  #   container_name: mongo-express
  #   image: mongo-express
  #   depends_on:
  #     - mongo
  #   ports:
  #     - "8888:8081"
  #   networks:
  #     - aicte-network   
  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    ports:
      - "4000:4000"
    volumes:
      - ./api-gateway:/app
    networks:
      - aicte-network
  auth:
    container_name: auth
    build: ./auth
    ports:
      - 4001:4000
    volumes:
      - ./auth:/app
    environment:
      - PORT=4000
      - CASSANDRA_HOST=cassandra.ap-south-1.amazonaws.com
      - CASSANDRA_REGION=ap-south-1
      - CASSANDRA_USERNAME=Divyanshu-at-179683962947
      - CASSANDRA_PASSWORD=rIB+JBT0gofd1TZFrTLq2Ras0nUBA+QO3yoOvu0iFnE=
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=auth
    networks:
      - aicte-network
  chat:
    container_name: chat
    build: ./chat
    ports:
      - 4002:4000
    volumes:
      - ./chat:/app
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=auth
      - MONGO_URI=mongodb://mongo:27017/chat
      - MONGO_USER=admin
      - MONGO_PASSWORD=admin
      - MONGO_DATABASE=chat
    networks:
      - aicte-network
networks:
  aicte-network:
    driver: bridge